# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QPushButton,QTextEdit,QLineEdit,QLabel
from As2_0 import doAs
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QTimer
opp = []#输出
ipt = ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','0') #输入 
class Ui_MainWindow(QtWidgets.QMainWindow):
    i = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(20, 10, 451, 31))
        self.input.setObjectName("input")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(490, 10, 161, 31))
        self.search.setObjectName("search")
        self.out = QtWidgets.QTextEdit(self.centralwidget)
        self.out.setGeometry(QtCore.QRect(490, 100, 261, 391))
        self.out.setObjectName("out")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(660, 50, 41, 31))
        self.stop.setObjectName("stop")
        self.con = QtWidgets.QPushButton(self.centralwidget)
        self.con.setGeometry(QtCore.QRect(490, 50, 161, 31))
        self.con.setObjectName("con")
        self.pre = QtWidgets.QPushButton(self.centralwidget)
        self.pre.setGeometry(QtCore.QRect(710, 10, 41, 31))
        self.pre.setObjectName("pre")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(710, 50, 41, 31))
        self.next.setObjectName("next")
        self.re = QtWidgets.QPushButton(self.centralwidget)
        self.re.setGeometry(QtCore.QRect(660, 10, 41, 31))
        self.re.setObjectName("re")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #初始块设置
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(30, 60, 101, 101))
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(140, 60, 101, 101))
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(250, 60, 101, 101))
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(360, 60, 101, 101))
        self.l4.setObjectName("l4")
        self.l8 = QtWidgets.QLabel(self.centralwidget)
        self.l8.setGeometry(QtCore.QRect(360, 170, 101, 101))
        self.l8.setObjectName("l8")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(140, 170, 101, 101))
        self.l6.setObjectName("l6")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(30, 170, 101, 101))
        self.l5.setObjectName("l5")
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(250, 170, 101, 101))
        self.l7.setObjectName("l7")
        self.l12 = QtWidgets.QLabel(self.centralwidget)
        self.l12.setGeometry(QtCore.QRect(360, 280, 101, 101))
        self.l12.setObjectName("l12")
        self.l16 = QtWidgets.QLabel(self.centralwidget)
        self.l16.setGeometry(QtCore.QRect(360, 390, 101, 101))
        self.l16.setObjectName("l16")
        self.l10 = QtWidgets.QLabel(self.centralwidget)
        self.l10.setGeometry(QtCore.QRect(140, 280, 101, 101))
        self.l10.setObjectName("l10")
        self.l13 = QtWidgets.QLabel(self.centralwidget)
        self.l13.setGeometry(QtCore.QRect(30, 390, 101, 101))
        self.l13.setObjectName("l13")
        self.l9 = QtWidgets.QLabel(self.centralwidget)
        self.l9.setGeometry(QtCore.QRect(30, 280, 101, 101))
        self.l9.setObjectName("l9")
        self.l11 = QtWidgets.QLabel(self.centralwidget)
        self.l11.setGeometry(QtCore.QRect(250, 280, 101, 101))
        self.l11.setObjectName("l11")
        self.l14 = QtWidgets.QLabel(self.centralwidget)
        self.l14.setGeometry(QtCore.QRect(140, 390, 101, 101))
        self.l14.setObjectName("l14")
        self.l15 = QtWidgets.QLabel(self.centralwidget)
        self.l15.setGeometry(QtCore.QRect(250, 390, 101, 101))
        self.l15.setObjectName("l15")
        MainWindow.setStatusBar(self.statusbar)

        #A*查找
        self.search.clicked.connect(self.doA)    
        #路径显示
        self.con.clicked.connect(self.play) 
        self.stop.clicked.connect(self.stopp)  
        self.re.clicked.connect(self.restart) 
        self.pre.clicked.connect(self.getpre)
        self.next.clicked.connect(self.getnxt)
         
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.stop.setText(_translate("MainWindow", "⏸"))
        self.con.setText(_translate("MainWindow", "Play"))
        self.pre.setText(_translate("MainWindow", "⏮"))
        self.next.setText(_translate("MainWindow", "⏭"))
        self.re.setText(_translate("MainWindow", "🔄"))

    def doA(self) :
        global opp
        global ipt
        opp.clear()
        del ipt
        ipt = tuple(self.input.text().split(' '))
        #设置初始状态
        self.startB(ipt)
        opp,time1,time2,nfn = doAs(ipt)
        for i in opp :
            temp = ''
            for j in range(16) :
                if j%4 ==3 :
                    temp += i[j] + ' ' + ' \n'
                    self.out.append(temp)
                    temp = ''
                else :
                    temp += i[j] + ' '   
            self.out.append('------------------')
        self.out.append("The number of steps : " + str(len(opp)-1))
        self.out.append("Timing: "+str(time2-time1))
        self.out.append("The number of expanded nodes :"+str(nfn))
    def startB(self,p) :
        pix = QPixmap('block/'+str(p[0])+'.png')
        self.l1.setPixmap(pix)
        pix = QPixmap('block/'+str(p[1])+'.png')
        self.l2.setPixmap(pix)
        pix = QPixmap('block/'+str(p[2])+'.png')
        self.l3.setPixmap(pix)
        pix = QPixmap('block/'+str(p[3])+'.png')
        self.l4.setPixmap(pix)
        pix = QPixmap('block/'+str(p[4])+'.png')
        self.l5.setPixmap(pix)
        pix = QPixmap('block/'+str(p[5])+'.png')
        self.l6.setPixmap(pix)
        pix = QPixmap('block/'+str(p[6])+'.png')
        self.l7.setPixmap(pix)
        pix = QPixmap('block/'+str(p[7])+'.png')
        self.l8.setPixmap(pix)
        pix = QPixmap('block/'+str(p[8])+'.png')
        self.l9.setPixmap(pix)
        pix = QPixmap('block/'+str(p[9])+'.png')
        self.l10.setPixmap(pix)
        pix = QPixmap('block/'+str(p[10])+'.png')
        self.l11.setPixmap(pix)
        pix = QPixmap('block/'+str(p[11])+'.png')
        self.l12.setPixmap(pix)
        pix = QPixmap('block/'+str(p[12])+'.png')
        self.l13.setPixmap(pix)
        pix = QPixmap('block/'+str(p[13])+'.png')
        self.l14.setPixmap(pix)
        pix = QPixmap('block/'+str(p[14])+'.png')
        self.l15.setPixmap(pix)
        pix = QPixmap('block/'+str(p[15])+'.png')
        self.l16.setPixmap(pix)
    
    def play(self) :
        self.timer=QTimer(self)
        self.timer.start(600)
        self.timer.timeout.connect(lambda:self.popp(opp[self.i]))
            
    def popp(self,p) :
        self.startB(p)
        self.i +=1
        if self.i==len(opp) :
            self.i = 0
            self.timer.stop()      
            
    def stopp(self) :
        self.timer.stop()
        
    def restart(self) :
        self.timer.stop()
        self.i = 0
        self.doA()
        self.play()
    
    def getpre(self) :
        if self.i >0 :
            self.i = self.i -1
            self.startB(opp[self.i])
        
    def getnxt(self) :
        
        if self.i +1<len(opp) :
            self.i = self.i +1
            self.startB(opp[self.i])
            
    '''def mov(self,p) :
        self.centralwidget.clearMask()
        for i in range(16) :
            x = 30 + (i%4)*110
            y = 60 + (i//4)*110
            self.l1 = QtWidgets.QLabel(self.centralwidget)
            self.l1.setGeometry(QtCore.QRect(x, y, 101, 101))
            pix = QPixmap('block/'+str(p[i])+'.png')
            self.l1.setPixmap(pix)'''
    